#!/bin/bash

AIlist=( 0 2 4 6 8 10 20 30 40 50 60 70 80 90 100 110 120 130 140 150 160 170 180 190 200 400 600 800 1000 1400 2000 2400 3000 3400 4000 )

SNo=50400002

resData='resData.txt'

if [ -e $resData ]
then
	echo removing $resData
	rm $resData
fi
touch $resData

for ai in "${AIlist[@]}"
do
	fill='fullT'$ai'SN'$SNo'.dat'
	outName='fullT'$ai'Out.log'
	
	nodeF='nodeFileT'$ai'.txt'
	volF='VoltageFileT'$ai'.txt'

	if [ -e $nodeF ]
	then
		cp $nodeF nodeFile.txt
		cp $volF VoltageFile.txt
                ./doSpice
        	echo $ai $(python3 spicePost.py 1) >> $resData
	else	 

		if [ -e $outName ]
		then
			python3 conductivityCalculations.py $ai > /dev/null
		else
			python3 conductivityCalculations.py $ai > $outName
		fi                 

		cp nodeFile.txt $nodeF
        	cp VoltageFile.txt $volF 
		./doSpice
		echo $ai $(python3 spicePost.py 1) >> $resData 
		rm nodeFile.cir
	fi

	cp spiceOut.txt 'spiceOut'$ai'.txt'

	echo $fill done

done
